name: PR Develop a Main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Clona repositorio
        uses: actions/checkout@v3

      - name: Setup de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instala dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecuta Dependabot
        uses: dependabot/dependabot-core@v1
        with:
          package-manager: 'pip'
          directory: '/'
          open-pull-requests-limit: 10

  codeql:
    runs-on: ubuntu-latest
    steps:
      - name: Clona repositorio
        uses: actions/checkout@v3

      - name: Inicializa CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      - name: Ejecuta CodeQL
        uses: github/codeql-action/analyze@v2

  pruebas-qa:
    runs-on: ubuntu-latest
    needs: [dependabot, codeql]
    steps:
      - name: Clona repositorio
        uses: actions/checkout@v3

      - name: Setup de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instala dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecuta pruebas de calidad
        run: |
          pytest
